
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 37
#define YY_END_OF_BUFFER 38
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[309] =
    {   0,
        0,    0,   38,   36,    1,    2,   14,   33,    9,   13,
       32,   15,   16,    6,   21,    6,   36,    9,    3,    3,
       22,   10,   11,   10,   27,   19,   20,   13,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   17,
       13,   18,    1,   10,   33,   26,    0,   12,    0,   31,
       32,    0,    7,    8,   29,    4,    0,    0,    4,    4,
       28,   28,    3,   13,   27,   27,   27,   27,   27,   27,
       23,   27,   27,   27,   23,   27,   27,   27,   27,   27,
       27,   26,    0,   33,    0,    0,    5,   32,   32,    0,
       29,   29,    0,   35,    0,    0,    0,   24,    0,    4,

       28,    0,    4,    3,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   23,   27,   27,   27,   27,   27,    0,
       30,    0,   32,   29,    4,    0,    0,   25,   24,    4,
       28,   34,    4,    3,   27,   27,   23,   27,   27,   27,
       27,   27,   27,   27,   27,    4,   35,    0,    0,   35,
       25,    4,   28,   34,    4,    3,   27,   23,   27,   27,
       27,   27,   27,   27,    0,   35,    0,    0,    4,   28,
        4,    3,   27,   27,   27,   23,   27,    4,   28,    4,
        3,   27,   27,   23,    4,   28,    4,    3,   27,   23,
        4,   28,    4,    3,   27,    4,   28,    4,    3,   27,

        4,   28,    4,    3,   27,    4,   28,    4,    3,   27,
        4,   28,    4,    3,   27,    4,   28,    4,    3,   27,
        4,   28,    4,    3,   27,    4,   28,    4,    3,   27,
        4,   28,    4,    3,   27,    4,   28,    4,    3,   27,
        4,   28,    4,    3,   27,    4,   28,    4,    3,   27,
        4,   28,    4,    3,   27,    4,   28,    4,    3,   27,
        4,   28,    4,    3,   27,    4,   28,    4,    3,   27,
        4,   28,    4,    3,   27,    4,   28,    4,    3,   27,
        4,   28,    4,    3,   27,    4,   28,    4,    3,   27,
        4,   28,    4,    3,   27,    4,   28,    4,    3,   27,

        4,   28,    4,    3,   27,   28,    4,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    1,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    6,    7,    1,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,    1,   21,   22,
       23,   24,    1,    1,   25,   25,   25,   25,   26,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       27,   28,   29,   30,   31,    1,   32,   33,   34,   35,

       36,   37,   25,   38,   39,   25,   40,   41,   25,   42,
       43,   44,   25,   45,   46,   47,   48,   49,   50,   25,
       25,   25,   51,   52,   53,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[54] =
    {   0,
        1,    2,    3,    1,    1,    1,    1,    1,    1,    4,
        1,    1,    1,    1,    1,    1,    5,    6,    7,    8,
        1,    1,    1,    1,    8,    8,    1,    2,    1,    1,
        9,    7,    7,    8,    8,    8,    7,    8,    8,    8,
        8,    7,    8,    8,    7,    8,    7,    8,    7,    8,
        1,    1,    1
    } ;

static const flex_int16_t yy_base[386] =
    {   0,
        0,    0,  519,  784,   52,  784,  492,   48,  784,  505,
       55,  784,  784,  498,  784,  492,   41,   46,   49,   53,
      784,   40,  484,   54,    0,  784,  784,  784,  461,   48,
       31,  464,   41,   50,  452,  457,  442,  447,  444,  784,
      426,  784,   86,  784,   74,  470,   90,  784,  448,  784,
       93,  465,  784,  784,   79,   87,   87,  106,  105,   95,
        0,  113,   97,  784,    0,  438,  427,  440,  428,  431,
      417,  411,  410,  402,    0,  392,  392,  376,  376,  368,
      360,  784,  119,  384,  100,    0,  784,  110,  120,  124,
      120,  125,  135,  143,  146,  144,  155,  784,  160,  116,

        0,  147,  157,  150,    0,  351,  339,  322,  312,  319,
      310,  299,  295,    0,  277,  263,  256,  260,  246,  161,
      784,    0,  173,  161,  165,  179,  180,  784,  191,  171,
        0,  183,  188,  190,    0,  239,    0,  232,  215,  216,
      206,  201,  196,  198,  188,  194,  199,  208,  205,  209,
      212,  209,    0,  214,  218,  220,    0,    0,  178,  158,
      159,  147,  137,  108,  229,  236,  237,    0,  226,    0,
      239,  232,    0,   95,   61,    0,   59,  241,    0,  245,
      247,    0,   35,    0,  249,    0,  253,  255,    0,    0,
      257,    0,  261,  263,    0,  265,    0,  269,  271,    0,

      273,    0,  277,  279,    0,  281,    0,  285,  287,    0,
      289,    0,  293,  295,    0,  297,    0,  301,  303,    0,
      305,    0,  309,  311,    0,  313,    0,  317,  319,    0,
      321,    0,  325,  327,    0,  329,    0,  333,  335,    0,
      337,    0,  341,  343,    0,  345,    0,  349,  351,    0,
      353,    0,  357,  359,    0,  361,    0,  365,  367,    0,
      369,    0,  373,  375,    0,  377,    0,  381,  383,    0,
      385,    0,  389,  391,    0,  393,    0,  397,  399,    0,
      401,    0,  405,  407,    0,  409,    0,  413,  415,    0,
      417,    0,  421,  423,    0,  425,    0,  429,  431,    0,

      435,    0,  439,  443,  784,  784,  447,  784,  479,  487,
      491,  494,  502,  509,  514,  521,  530,  533,  536,  544,
      549,  555,  563,  566,  569,  575,  582,  591,  594,  597,
      606,  609,  612,  621,  624,  627,  630,  633,  636,  639,
      642,  645,  648,  651,  654,  657,  660,  663,  666,  669,
      672,  675,  678,  681,  684,  687,  690,  693,  696,  699,
      702,  705,  708,  711,  714,  717,  720,  723,  726,  729,
      732,  735,  738,  741,  744,  747,  750,  753,  756,  759,
      762,  765,  768,  771,  774
    } ;

static const flex_int16_t yy_def[386] =
    {   0,
      308,    1,  308,  308,  308,  308,  308,  309,  308,  308,
      310,  308,  308,  308,  308,  308,  308,  308,  311,  311,
      308,  308,  308,  308,  312,  308,  308,  308,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  308,
      308,  308,  308,  308,  309,  308,  309,  308,  313,  308,
      314,  315,  308,  308,  308,  308,  316,  317,  308,   20,
      318,  318,   20,  308,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  308,  309,  308,  320,  321,  308,  322,  313,  313,
      308,  308,  308,  316,  316,  323,  317,  308,  317,   20,

      324,  308,  324,   20,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  320,
      308,  326,  322,  308,  308,  327,  328,  308,  317,   20,
      329,  308,  329,   20,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  308,  327,  327,  323,  327,
      331,   20,  332,  308,  332,   20,  333,  333,  333,  333,
      333,  333,  333,  333,  328,  331,  331,  334,   20,  335,
      335,   20,  336,  336,  336,  336,  336,   20,  337,  337,
       20,  338,  338,  338,   20,  339,  339,   20,  340,  340,
       20,  341,  341,   20,  342,   20,  343,  343,   20,  344,

       20,  345,  345,   20,  346,   20,  347,  347,   20,  348,
       20,  349,  349,   20,  350,   20,  351,  351,   20,  352,
       20,  353,  353,   20,  354,   20,  355,  355,   20,  356,
       20,  357,  357,   20,  358,   20,  359,  359,   20,  360,
       20,  361,  361,   20,  362,   20,  363,  363,   20,  364,
       20,  365,  365,   20,  366,   20,  367,  367,   20,  368,
       20,  369,  369,   20,  370,   20,  371,  371,   20,  372,
       20,  373,  373,   20,  374,   20,  375,  375,   20,  376,
       20,  377,  377,   20,  378,   20,  379,  379,   20,  380,
       20,  381,  381,   20,  382,   20,  383,  383,   20,  384,

      308,  385,  385,  308,  308,  308,  308,    0,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308
    } ;

static const flex_int16_t yy_nxt[838] =
    {   0,
        4,    5,    6,    5,    4,    7,    8,    9,   10,   11,
       12,   13,    9,   14,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   25,   26,    4,   27,   28,
       25,   25,   29,   30,   31,   32,   33,   25,   34,   25,
       25,   25,   25,   35,   36,   37,   25,   25,   38,   39,
       40,   41,   42,   43,   46,   43,   49,   55,   57,   56,
       56,   64,   44,   58,   50,   59,   70,   60,   60,   59,
      190,   63,   63,   71,   62,   47,   44,   64,   62,   67,
       46,   73,   52,   74,   62,   68,   75,   43,   62,   43,
       69,   76,   83,   95,   85,   91,   84,   92,   92,   96,

      184,   47,   87,   55,   95,   56,   56,  184,   98,  121,
       98,  120,   93,  100,  100,  104,  104,   47,   99,  121,
       86,   55,   93,   56,   56,   84,  102,  122,  102,   87,
       93,  103,  103,   87,  130,  130,   91,  122,  124,  124,
       93,   91,  183,   92,   92,  176,   47,   86,  102,   95,
      102,   86,   95,  125,  125,   96,  127,   98,   96,   98,
       95,  128,   98,   95,   98,  125,  125,   99,  134,  134,
      121,  129,   99,  132,  120,  133,  133,   91,  176,  124,
      124,  132,  121,  146,  146,  148,  126,  177,  122,  152,
      152,  149,   96,   98,  176,   98,  148,  151,  175,  132,

      122,  154,  154,   99,  132,  148,  155,  155,  156,  156,
      132,  149,  146,  146,  148,  148,  148,  165,  167,  174,
      149,  149,  128,  158,  168,  148,  148,  169,  169,  167,
      132,  164,  154,  154,  132,  126,  171,  171,  172,  172,
      163,  149,  167,  167,  178,  178,  151,  162,  168,  168,
      181,  181,  158,  167,  167,  132,  161,  180,  180,  185,
      185,  132,  160,  187,  187,  188,  188,  191,  191,  132,
      159,  193,  193,  194,  194,  196,  196,  132,  158,  198,
      198,  199,  199,  201,  201,  132,  145,  203,  203,  204,
      204,  206,  206,  132,  137,  208,  208,  209,  209,  211,

      211,  132,  144,  213,  213,  214,  214,  216,  216,  132,
      143,  218,  218,  219,  219,  221,  221,  132,  142,  223,
      223,  224,  224,  226,  226,  132,  141,  228,  228,  229,
      229,  231,  231,  132,  137,  233,  233,  234,  234,  236,
      236,  132,  140,  238,  238,  239,  239,  241,  241,  132,
      139,  243,  243,  244,  244,  246,  246,  132,  138,  248,
      248,  249,  249,  251,  251,  132,  137,  253,  253,  254,
      254,  256,  256,  132,  137,  258,  258,  259,  259,  261,
      261,  132,  136,  263,  263,  264,  264,  266,  266,  132,
       82,  268,  268,  269,  269,  271,  271,  132,  119,  273,

      273,  274,  274,  276,  276,  132,  118,  278,  278,  279,
      279,  281,  281,  132,  117,  283,  283,  284,  284,  286,
      286,  132,  116,  288,  288,  289,  289,  291,  291,  132,
      115,  293,  293,  294,  294,  296,  296,  132,  114,  298,
      298,  299,  299,  301,  301,  132,  114,  303,  303,  304,
      304,   59,  113,  301,  301,  132,  112,  307,  307,   59,
       93,  304,  304,  132,  111,  146,  146,  110,   93,  109,
       93,  108,  107,  106,   89,   86,   82,   48,   93,   45,
       45,   81,   45,   45,   45,   45,   45,   45,   51,   80,
       51,   79,   78,   51,   51,   61,   77,   61,   61,   61,

       65,   65,   65,   85,   72,   66,   44,   54,   85,   85,
       88,   53,   88,   48,   44,   88,   88,   90,  308,  308,
       90,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       97,   97,   97,   97,   97,   97,   97,   97,   97,  101,
      101,  101,  105,  105,  105,  120,  308,  120,  308,  308,
      120,  120,   85,  308,  308,   85,  123,  308,  123,  308,
      308,  123,  123,  126,  126,  126,  126,  126,  126,  126,
      126,  126,  131,  131,  131,  135,  135,  135,  120,  308,
      308,  120,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  150,  150,  150,  150,  150,  150,  150,  150,  150,

      153,  153,  153,  157,  157,  157,  166,  166,  166,  166,
      166,  166,  166,  166,  166,  170,  170,  170,  173,  173,
      173,  167,  167,  167,  167,  167,  308,  167,  167,  167,
      179,  179,  179,  182,  182,  182,  186,  186,  186,  189,
      189,  189,  192,  192,  192,  195,  195,  195,  197,  197,
      197,  200,  200,  200,  202,  202,  202,  205,  205,  205,
      207,  207,  207,  210,  210,  210,  212,  212,  212,  215,
      215,  215,  217,  217,  217,  220,  220,  220,  222,  222,
      222,  225,  225,  225,  227,  227,  227,  230,  230,  230,
      232,  232,  232,  235,  235,  235,  237,  237,  237,  240,

      240,  240,  242,  242,  242,  245,  245,  245,  247,  247,
      247,  250,  250,  250,  252,  252,  252,  255,  255,  255,
      257,  257,  257,  260,  260,  260,  262,  262,  262,  265,
      265,  265,  267,  267,  267,  270,  270,  270,  272,  272,
      272,  275,  275,  275,  277,  277,  277,  280,  280,  280,
      282,  282,  282,  285,  285,  285,  287,  287,  287,  290,
      290,  290,  292,  292,  292,  295,  295,  295,  297,  297,
      297,  300,  300,  300,  302,  302,  302,  305,  305,  305,
      306,  306,  306,    3,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,

      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308
    } ;

static const flex_int16_t yy_chk[838] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    5,    8,    5,   11,   17,   18,   17,
       17,   22,   22,   18,   11,   19,   31,   19,   19,   20,
      183,   20,   20,   31,   19,    8,   24,   24,   20,   30,
       45,   33,   11,   33,   19,   30,   34,   43,   20,   43,
       30,   34,   47,   57,   51,   55,   47,   55,   55,   57,

      177,   45,   51,   56,   57,   56,   56,  175,   58,   85,
       58,   88,   56,   60,   60,   63,   63,   47,   58,   88,
       51,   59,   56,   59,   59,   83,   62,   85,   62,   89,
       59,   62,   62,   90,  100,  100,   91,   88,   91,   91,
       59,   92,  174,   92,   92,  164,   83,   89,   93,   94,
       93,   90,   95,   93,   93,   94,   96,   97,   95,   97,
       94,   96,   99,   95,   99,  102,  102,   97,  104,  104,
      120,   99,   99,  103,  123,  103,  103,  124,  163,  124,
      124,  125,  123,  125,  125,  126,  127,  162,  120,  130,
      130,  126,  127,  129,  161,  129,  126,  127,  160,  132,

      123,  132,  132,  129,  133,  147,  133,  133,  134,  134,
      146,  147,  146,  146,  148,  150,  147,  149,  151,  159,
      148,  150,  149,  145,  151,  148,  150,  152,  152,  151,
      154,  144,  154,  154,  155,  165,  155,  155,  156,  156,
      143,  165,  166,  167,  169,  169,  165,  142,  166,  167,
      172,  172,  141,  166,  167,  171,  140,  171,  171,  178,
      178,  180,  139,  180,  180,  181,  181,  185,  185,  187,
      138,  187,  187,  188,  188,  191,  191,  193,  136,  193,
      193,  194,  194,  196,  196,  198,  119,  198,  198,  199,
      199,  201,  201,  203,  118,  203,  203,  204,  204,  206,

      206,  208,  117,  208,  208,  209,  209,  211,  211,  213,
      116,  213,  213,  214,  214,  216,  216,  218,  115,  218,
      218,  219,  219,  221,  221,  223,  113,  223,  223,  224,
      224,  226,  226,  228,  112,  228,  228,  229,  229,  231,
      231,  233,  111,  233,  233,  234,  234,  236,  236,  238,
      110,  238,  238,  239,  239,  241,  241,  243,  109,  243,
      243,  244,  244,  246,  246,  248,  108,  248,  248,  249,
      249,  251,  251,  253,  107,  253,  253,  254,  254,  256,
      256,  258,  106,  258,  258,  259,  259,  261,  261,  263,
       84,  263,  263,  264,  264,  266,  266,  268,   81,  268,

      268,  269,  269,  271,  271,  273,   80,  273,  273,  274,
      274,  276,  276,  278,   79,  278,  278,  279,  279,  281,
      281,  283,   78,  283,  283,  284,  284,  286,  286,  288,
       77,  288,  288,  289,  289,  291,  291,  293,   76,  293,
      293,  294,  294,  296,  296,  298,   74,  298,  298,  299,
      299,  301,   73,  301,  301,  303,   72,  303,  303,  304,
      301,  304,  304,  307,   71,  307,  307,   70,  304,   69,
      301,   68,   67,   66,   52,   49,   46,   41,  304,  309,
      309,   39,  309,  309,  309,  309,  309,  309,  310,   38,
      310,   37,   36,  310,  310,  311,   35,  311,  311,  311,

      312,  312,  312,  313,   32,   29,   23,   16,  313,  313,
      314,   14,  314,   10,    7,  314,  314,  315,    3,    0,
      315,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  318,
      318,  318,  319,  319,  319,  320,    0,  320,    0,    0,
      320,  320,  321,    0,    0,  321,  322,    0,  322,    0,
        0,  322,  322,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  324,  324,  324,  325,  325,  325,  326,    0,
        0,  326,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  328,  328,  328,  328,  328,  328,  328,  328,  328,

      329,  329,  329,  330,  330,  330,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  332,  332,  332,  333,  333,
      333,  334,  334,  334,  334,  334,    0,  334,  334,  334,
      335,  335,  335,  336,  336,  336,  337,  337,  337,  338,
      338,  338,  339,  339,  339,  340,  340,  340,  341,  341,
      341,  342,  342,  342,  343,  343,  343,  344,  344,  344,
      345,  345,  345,  346,  346,  346,  347,  347,  347,  348,
      348,  348,  349,  349,  349,  350,  350,  350,  351,  351,
      351,  352,  352,  352,  353,  353,  353,  354,  354,  354,
      355,  355,  355,  356,  356,  356,  357,  357,  357,  358,

      358,  358,  359,  359,  359,  360,  360,  360,  361,  361,
      361,  362,  362,  362,  363,  363,  363,  364,  364,  364,
      365,  365,  365,  366,  366,  366,  367,  367,  367,  368,
      368,  368,  369,  369,  369,  370,  370,  370,  371,  371,
      371,  372,  372,  372,  373,  373,  373,  374,  374,  374,
      375,  375,  375,  376,  376,  376,  377,  377,  377,  378,
      378,  378,  379,  379,  379,  380,  380,  380,  381,  381,
      381,  382,  382,  382,  383,  383,  383,  384,  384,  384,
      385,  385,  385,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,

      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[38] =
    {   0,
0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "1605115_scanner.l"
#line 5 "1605115_scanner.l"
#define YYSTYPE SymbolInfo*

#include<bits/stdc++.h>
#include "1605115_symboltable.h"
#include "y.tab.h"

using namespace std;

int word_count=0;
int err_count = 0;

extern ofstream logfile;
extern int line_no;
//log and error file defined in parser. 


extern YYSTYPE yylval;


void updateLineNo(int line) {
	line_no = line;
}

void startLogLine(int line_no) {
//	cout<< "\nLine No. " << line_no << ": ";
	
}

string getUpper(string input) {
	string yytextString(input);
	 transform(yytextString.begin(), yytextString.end(),yytextString.begin(), ::toupper);
	 return yytextString;
}

void updateLogFile(string tokenType, string symbolName, int line_no ) {
 startLogLine(line_no);
 //cout << "Token <" << tokenType << "> lexeme " << symbolName << " Found" << endl;
}

void updateLogWithError(string errorType, string symbolName, int line_no) {
//	cout << "\nError at line " << line_no << ": " << errorType << " " << symbolName << endl;
}


void updateTokenFile(string tokenType, string symbolName) {
	
	//cout << "<" << tokenType << ", " << symbolName << "> ";
}

void IncWc(){
	word_count++;
}

SymbolInfo* getSymbolInfo(string name, string type) {
	SymbolInfo* ret = new SymbolInfo(name, type);

	return ret; 
}

string stringFormatter(string input) {

    string str = input, temp, res = "";
    int s = 0, l = str.length();
    for(int i=0; i<(l-1); i++) {
        if(str[i]=='\\') {
            temp = str.substr(s,i-s);
            char c = str[i+1];
            if(c=='a') temp.push_back('\a');
            else if(c=='b') temp.push_back('\b');
            else if(c=='n') temp.push_back('\n');
            else if(c=='t') temp.push_back('\t');
            else if(c=='f') temp.push_back('\f');
            else if(c=='v') temp.push_back('\v');
            else if(c=='r') temp.push_back('\r');
            else if(c=='0') temp.push_back('\0');
            else if(c=='\"') temp.push_back('\"');
            else if(c=='\\') temp.push_back('\\');
            res = res + temp;
            s = i+2;
        }
    }
    res = res + str.substr(s,l-s);
		

	return res;
}

#line 859 "lex.yy.c"
#line 860 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 123 "1605115_scanner.l"



#line 1081 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 309 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 784 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 126 "1605115_scanner.l"
{}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 127 "1605115_scanner.l"
{}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 132 "1605115_scanner.l"
{
	return 0;
	//todo might need to change. Not sure if we need to return.
	}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 137 "1605115_scanner.l"
{string symbol(yytext);
	updateLineNo(yylineno);
 	yylval = getSymbolInfo(symbol, "CONST_INT");
	return CONST_INT; 
 }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 143 "1605115_scanner.l"
{string symbol(yytext);
 	yylval = getSymbolInfo(symbol, "CONST_FLOAT");
	updateLineNo(yylineno);
 	return CONST_FLOAT; 	
 }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 150 "1605115_scanner.l"
{string symbol(yytext);
 //updateLogFile("CHAR_CONST", symbol, yylineno);
 symbol = stringFormatter(symbol);
 updateLineNo(yylineno);
 	
 symbol = symbol.substr(1, symbol.size() - 2);
	//yylval = getSymbolInfo(symbol, "CONST_CHAR");
	//return CONST_CHAR;
//todo probably remove this because does not match to any grammar in the parser.??
 	}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 164 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	string symbol(yytext);
	yylval = getSymbolInfo(symbol, "ADDOP");
	return ADDOP;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 171 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	string symbol(yytext);
	yylval = getSymbolInfo(symbol, "INCOP");
	return INCOP;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 179 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	string symbol(yytext);
	yylval = getSymbolInfo(symbol, "DECOP");
	return DECOP;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 187 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	string symbol(yytext);
	yylval = getSymbolInfo(symbol, "MULOP");
	return MULOP;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 194 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	string symbol(yytext);
	yylval = getSymbolInfo(symbol, "RELOP");
	return RELOP;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 201 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	string symbol(yytext);
	yylval = getSymbolInfo(symbol, "ASSIGNOP");
	return ASSIGNOP;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 208 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	string symbol(yytext);
	yylval = getSymbolInfo(symbol, "LOGICOP");
	return LOGICOP;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 215 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	string symbol(yytext);
	yylval = getSymbolInfo(symbol, "BITOP");
	return BITOP;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 222 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	string symbol(yytext);
	yylval = getSymbolInfo(symbol, "NOT");
	return NOT;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 229 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	string symbol(yytext);
		yylval = getSymbolInfo(symbol, "LPAREN");

	return LPAREN; 
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 237 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	string symbol(yytext);
	yylval = getSymbolInfo(symbol, "RPAREN");
	return RPAREN; 
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 244 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	string symbol(yytext);
	yylval = getSymbolInfo(symbol, "LCURL");
	return LCURL; 
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 251 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	string symbol(yytext);
	yylval = getSymbolInfo(symbol, "RCURL");
	return RCURL;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 258 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	string symbol(yytext);
	yylval = getSymbolInfo(symbol, "LTHIRD");
	return LTHIRD;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 265 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	string symbol(yytext);
	yylval = getSymbolInfo(symbol, "RTHIRD");
	return RTHIRD; 
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 272 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	string symbol(yytext);
	yylval = getSymbolInfo(symbol, "COMMA");
	return COMMA; 
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 279 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	string symbol(yytext);
	yylval = getSymbolInfo(symbol, "SEMICOLON");
	return SEMICOLON;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 286 "1605115_scanner.l"
{ updateLineNo(yylineno);
 	
	string yyString(yytext); string yytextString = getUpper(yyString);
	//startLogLine(yylineno); logstream << "Token <" << yytextString << "> Lexeme " << yytext << " found" << endl;
	//tokenstream << "<" << yytextString << "> ";
	//if|for|do|int|float|void|switch|else|default|while|break|char|double|return|case|continue
	
		yylval = getSymbolInfo(yyString, yytextString);

	if(yytextString == "IF") {
		return IF;
	} else if (yytextString == "FOR") {
		return FOR;
	} else if (yytextString == "DO" ) {
		return DO;
	} else if (yytextString == "INT") {
		return INT;
	} else if (yytextString == "FLOAT") {
		return FLOAT;
	} else if (yytextString == "VOID") {
		return VOID;
	} else if (yytextString == "SWITCH") {
		return SWITCH;
	} else if (yytextString == "ELSE") {
		return ELSE;
	} else if (yytextString == "DEFAULT") {
		return DEFAULT;
	} else if (yytextString == "WHILE") {
		return WHILE;
	} else if (yytextString == "BREAK") {
		return BREAK;
	} else if (yytextString == "CHAR") {
		return CHAR;
	} else if (yytextString == "DOUBLE") {
		return DOUBLE;
	} else if (yytextString == "RETURN") {
		return RETURN;
	} else if (yytextString == "CASE") {
		return CASE;
	} else if (yytextString == "CONTINUE") {
		return CONTINUE;
	} else if (yytextString == "PRINTLN") {
		return PRINTLN; 
	}
	
}
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 333 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	string symbol(yytext);

}
	YY_BREAK
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 338 "1605115_scanner.l"
{updateLineNo(yylineno);
 	string symbol(yytext); }
	YY_BREAK
case 26:
/* rule 26 can match eol */
YY_RULE_SETUP
#line 343 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	
 }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 349 "1605115_scanner.l"
{updateLineNo(yylineno);
 	 string symbol(yytext);  
yylval = getSymbolInfo(symbol, "ID");
return ID; 
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 359 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	//INVALID PREFIX ON ID OR INVALID SUFFIX ON NUMBER
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 364 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	//TOO MANY DECILMAL POINT ERROR 
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 369 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	//MULTI CHARACTER COUNT ERROR 
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 374 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	//EMPTY CHARACTER CONSTANT ERROR 
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 379 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	//UNTERMINATE CAHRACTER ERROR 
}
	YY_BREAK
case 33:
/* rule 33 can match eol */
YY_RULE_SETUP
#line 384 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	//UNTERMINATED STRING ERROR 

}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 391 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	//ILL FORMED NUMBER 
}
	YY_BREAK
case 35:
/* rule 35 can match eol */
YY_RULE_SETUP
#line 396 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	//UNFINISHED COMMENT 
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 403 "1605115_scanner.l"
{ updateLineNo(yylineno);
 	
	//UNRECOGNIZED CHARACTER
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 408 "1605115_scanner.l"
ECHO;
	YY_BREAK
#line 1534 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 309 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 309 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 308);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 408 "1605115_scanner.l"



