
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 36
#define YY_END_OF_BUFFER 37
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[302] =
    {   0,
        0,    0,   37,   35,    1,    2,   13,   32,    8,   12,
       31,   14,   15,    6,   20,    6,   35,    8,    3,    3,
       21,    9,   10,    9,   26,   18,   19,   12,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   16,   12,
       17,    1,    9,   32,   25,    0,   11,    0,   30,   31,
        0,    7,   28,    4,    0,    0,    4,    4,   27,   27,
        3,   12,   26,   26,   26,   26,   26,   26,   22,   26,
       26,   26,   22,   26,   26,   26,   26,   26,   25,    0,
       32,    0,    0,    5,   31,   31,    0,   28,   28,    0,
       34,    0,    0,    0,   23,    0,    4,   27,    0,    4,

        3,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       22,   26,   26,   26,   26,    0,   29,    0,   31,   28,
        4,    0,    0,   24,   23,    4,   27,   33,    4,    3,
       26,   26,   22,   26,   26,   26,   26,   26,   26,   26,
        4,   34,    0,    0,   34,   24,    4,   27,   33,    4,
        3,   26,   22,   26,   26,   26,   26,   26,    0,   34,
        0,    0,    4,   27,    4,    3,   26,   26,   26,   22,
        4,   27,    4,    3,   26,   26,   22,    4,   27,    4,
        3,   26,   22,    4,   27,    4,    3,   26,    4,   27,
        4,    3,   26,    4,   27,    4,    3,   26,    4,   27,

        4,    3,   26,    4,   27,    4,    3,   26,    4,   27,
        4,    3,   26,    4,   27,    4,    3,   26,    4,   27,
        4,    3,   26,    4,   27,    4,    3,   26,    4,   27,
        4,    3,   26,    4,   27,    4,    3,   26,    4,   27,
        4,    3,   26,    4,   27,    4,    3,   26,    4,   27,
        4,    3,   26,    4,   27,    4,    3,   26,    4,   27,
        4,    3,   26,    4,   27,    4,    3,   26,    4,   27,
        4,    3,   26,    4,   27,    4,    3,   26,    4,   27,
        4,    3,   26,    4,   27,    4,    3,   26,    4,   27,
        4,    3,   26,    4,   27,    4,    3,   26,   27,    4,

        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    1,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    6,    7,    1,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,    1,   21,   22,
       23,   24,    1,    1,   25,   25,   25,   25,   26,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       27,   28,   29,   30,   31,    1,   32,   33,   34,   35,

       36,   37,   25,   38,   39,   25,   40,   41,   25,   42,
       43,   25,   25,   44,   45,   46,   47,   48,   49,   25,
       25,   25,   50,   51,   52,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[53] =
    {   0,
        1,    2,    3,    1,    1,    1,    1,    1,    1,    4,
        1,    1,    1,    1,    1,    1,    5,    6,    7,    8,
        1,    1,    1,    1,    8,    8,    1,    2,    1,    1,
        9,    7,    7,    8,    8,    8,    7,    8,    8,    8,
        8,    7,    8,    7,    8,    7,    8,    7,    8,    1,
        1,    1
    } ;

static const flex_int16_t yy_base[379] =
    {   0,
        0,    0,  505,  783,   51,  783,  481,   47,  783,  487,
       54,  783,  783,  478,  783,  475,   40,   45,   48,   52,
      783,   39,  466,   53,    0,  783,  783,  783,  437,   47,
       30,  436,   40,   49,  440,  426,  431,  435,  783,  421,
      783,   85,  783,   73,  464,   89,  783,  441,  783,   92,
      457,  783,   78,   86,   86,  105,  104,   94,    0,  112,
       96,  783,    0,  428,  411,  420,  404,  401,  383,  377,
      371,  362,    0,  352,  344,  343,  335,  327,  783,  118,
      351,   99,    0,  783,  109,  119,  123,  119,  124,  134,
      142,  145,  143,  154,  783,  159,  115,    0,  146,  156,

      149,    0,  318,  306,  290,  280,  286,  277,  266,  262,
        0,  239,  232,  235,  221,  160,  783,    0,  172,  160,
      164,  178,  179,  783,  190,  170,    0,  182,  187,  189,
        0,  216,    0,  213,  200,  199,  185,  179,  185,  162,
      193,  198,  207,  204,  208,  211,  208,    0,  213,  217,
      219,    0,    0,  152,  146,  142,  103,  104,  228,  235,
      236,    0,  225,    0,  238,  231,    0,   60,   54,    0,
      240,    0,  244,  246,    0,   34,    0,  248,    0,  252,
      254,    0,    0,  256,    0,  260,  262,    0,  264,    0,
      268,  270,    0,  272,    0,  276,  278,    0,  280,    0,

      284,  286,    0,  288,    0,  292,  294,    0,  296,    0,
      300,  302,    0,  304,    0,  308,  310,    0,  312,    0,
      316,  318,    0,  320,    0,  324,  326,    0,  328,    0,
      332,  334,    0,  336,    0,  340,  342,    0,  344,    0,
      348,  350,    0,  352,    0,  356,  358,    0,  360,    0,
      364,  366,    0,  368,    0,  372,  374,    0,  376,    0,
      380,  382,    0,  384,    0,  388,  390,    0,  392,    0,
      396,  398,    0,  400,    0,  404,  406,    0,  408,    0,
      412,  414,    0,  416,    0,  420,  422,    0,  424,    0,
      428,  430,    0,  434,    0,  438,  442,  783,  783,  446,

      783,  478,  486,  490,  493,  501,  508,  513,  520,  529,
      532,  535,  543,  548,  554,  562,  565,  568,  574,  581,
      590,  593,  596,  605,  608,  611,  620,  623,  626,  629,
      632,  635,  638,  641,  644,  647,  650,  653,  656,  659,
      662,  665,  668,  671,  674,  677,  680,  683,  686,  689,
      692,  695,  698,  701,  704,  707,  710,  713,  716,  719,
      722,  725,  728,  731,  734,  737,  740,  743,  746,  749,
      752,  755,  758,  761,  764,  767,  770,  773
    } ;

static const flex_int16_t yy_def[379] =
    {   0,
      301,    1,  301,  301,  301,  301,  301,  302,  301,  301,
      303,  301,  301,  301,  301,  301,  301,  301,  304,  304,
      301,  301,  301,  301,  305,  301,  301,  301,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  301,  301,
      301,  301,  301,  302,  301,  302,  301,  306,  301,  307,
      308,  301,  301,  301,  309,  310,  301,   20,  311,  311,
       20,  301,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  301,  302,
      301,  313,  314,  301,  315,  306,  306,  301,  301,  301,
      309,  309,  316,  310,  301,  310,   20,  317,  301,  317,

       20,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  313,  301,  319,  315,  301,
      301,  320,  321,  301,  310,   20,  322,  301,  322,   20,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      301,  320,  320,  316,  320,  324,   20,  325,  301,  325,
       20,  326,  326,  326,  326,  326,  326,  326,  321,  324,
      324,  327,   20,  328,  328,   20,  329,  329,  329,  329,
       20,  330,  330,   20,  331,  331,  331,   20,  332,  332,
       20,  333,  333,   20,  334,  334,   20,  335,   20,  336,
      336,   20,  337,   20,  338,  338,   20,  339,   20,  340,

      340,   20,  341,   20,  342,  342,   20,  343,   20,  344,
      344,   20,  345,   20,  346,  346,   20,  347,   20,  348,
      348,   20,  349,   20,  350,  350,   20,  351,   20,  352,
      352,   20,  353,   20,  354,  354,   20,  355,   20,  356,
      356,   20,  357,   20,  358,  358,   20,  359,   20,  360,
      360,   20,  361,   20,  362,  362,   20,  363,   20,  364,
      364,   20,  365,   20,  366,  366,   20,  367,   20,  368,
      368,   20,  369,   20,  370,  370,   20,  371,   20,  372,
      372,   20,  373,   20,  374,  374,   20,  375,   20,  376,
      376,   20,  377,  301,  378,  378,  301,  301,  301,  301,

        0,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301
    } ;

static const flex_int16_t yy_nxt[836] =
    {   0,
        4,    5,    6,    5,    4,    7,    8,    9,   10,   11,
       12,   13,    9,   14,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   25,   26,    4,   27,   28,
       25,   25,   29,   30,   31,   32,   33,   25,   34,   25,
       25,   25,   25,   35,   36,   25,   25,   37,   38,   39,
       40,   41,   42,   45,   42,   48,   53,   55,   54,   54,
       62,   43,   56,   49,   57,   68,   58,   58,   57,  183,
       61,   61,   69,   60,   46,   43,   62,   60,   65,   45,
       71,   51,   72,   60,   66,   73,   42,   60,   42,   67,
       74,   80,   92,   82,   88,   81,   89,   89,   93,  177,

       46,   84,   53,   92,   54,   54,  176,   95,  117,   95,
      116,   90,   97,   97,  101,  101,   46,   96,  117,   83,
       53,   90,   54,   54,   81,   99,  118,   99,   84,   90,
      100,  100,   84,  126,  126,   88,  118,  120,  120,   90,
       88,  170,   89,   89,  170,   46,   83,   99,   92,   99,
       83,   92,  121,  121,   93,  123,   95,   93,   95,   92,
      124,   95,   92,   95,  121,  121,   96,  130,  130,  117,
      125,   96,  128,  116,  129,  129,   88,  170,  120,  120,
      128,  117,  141,  141,  143,  122,  169,  118,  147,  147,
      144,   93,   95,  168,   95,  143,  146,  153,  128,  118,

      149,  149,   96,  128,  143,  150,  150,  151,  151,  128,
      144,  141,  141,  143,  143,  143,  159,  161,  158,  144,
      144,  124,  157,  162,  143,  143,  163,  163,  161,  128,
      153,  149,  149,  128,  122,  165,  165,  166,  166,  156,
      144,  161,  161,  171,  171,  146,  155,  162,  162,  174,
      174,  154,  161,  161,  128,  153,  173,  173,  178,  178,
      128,  140,  180,  180,  181,  181,  184,  184,  128,  133,
      186,  186,  187,  187,  189,  189,  128,  139,  191,  191,
      192,  192,  194,  194,  128,  138,  196,  196,  197,  197,
      199,  199,  128,  137,  201,  201,  202,  202,  204,  204,

      128,  133,  206,  206,  207,  207,  209,  209,  128,  136,
      211,  211,  212,  212,  214,  214,  128,  135,  216,  216,
      217,  217,  219,  219,  128,  134,  221,  221,  222,  222,
      224,  224,  128,  133,  226,  226,  227,  227,  229,  229,
      128,  133,  231,  231,  232,  232,  234,  234,  128,  132,
      236,  236,  237,  237,  239,  239,  128,   79,  241,  241,
      242,  242,  244,  244,  128,  115,  246,  246,  247,  247,
      249,  249,  128,  114,  251,  251,  252,  252,  254,  254,
      128,  113,  256,  256,  257,  257,  259,  259,  128,  112,
      261,  261,  262,  262,  264,  264,  128,  111,  266,  266,

      267,  267,  269,  269,  128,  111,  271,  271,  272,  272,
      274,  274,  128,  110,  276,  276,  277,  277,  279,  279,
      128,  109,  281,  281,  282,  282,  284,  284,  128,  108,
      286,  286,  287,  287,  289,  289,  128,  107,  291,  291,
      292,  292,  294,  294,  128,  106,  296,  296,  297,  297,
       57,  105,  294,  294,  128,  104,  300,  300,   57,   90,
      297,  297,  128,  103,  141,  141,   86,   90,   83,   90,
       79,   47,   78,   77,   76,   75,   70,   90,   44,   44,
       64,   44,   44,   44,   44,   44,   44,   50,   43,   50,
       52,   52,   50,   50,   59,   47,   59,   59,   59,   63,

       63,   63,   82,   43,  301,  301,  301,   82,   82,   85,
      301,   85,  301,  301,   85,   85,   87,  301,  301,   87,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   98,   98,
       98,  102,  102,  102,  116,  301,  116,  301,  301,  116,
      116,   82,  301,  301,   82,  119,  301,  119,  301,  301,
      119,  119,  122,  122,  122,  122,  122,  122,  122,  122,
      122,  127,  127,  127,  131,  131,  131,  116,  301,  301,
      116,  142,  142,  142,  142,  142,  142,  142,  142,  142,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  148,

      148,  148,  152,  152,  152,  160,  160,  160,  160,  160,
      160,  160,  160,  160,  164,  164,  164,  167,  167,  167,
      161,  161,  161,  161,  161,  301,  161,  161,  161,  172,
      172,  172,  175,  175,  175,  179,  179,  179,  182,  182,
      182,  185,  185,  185,  188,  188,  188,  190,  190,  190,
      193,  193,  193,  195,  195,  195,  198,  198,  198,  200,
      200,  200,  203,  203,  203,  205,  205,  205,  208,  208,
      208,  210,  210,  210,  213,  213,  213,  215,  215,  215,
      218,  218,  218,  220,  220,  220,  223,  223,  223,  225,
      225,  225,  228,  228,  228,  230,  230,  230,  233,  233,

      233,  235,  235,  235,  238,  238,  238,  240,  240,  240,
      243,  243,  243,  245,  245,  245,  248,  248,  248,  250,
      250,  250,  253,  253,  253,  255,  255,  255,  258,  258,
      258,  260,  260,  260,  263,  263,  263,  265,  265,  265,
      268,  268,  268,  270,  270,  270,  273,  273,  273,  275,
      275,  275,  278,  278,  278,  280,  280,  280,  283,  283,
      283,  285,  285,  285,  288,  288,  288,  290,  290,  290,
      293,  293,  293,  295,  295,  295,  298,  298,  298,  299,
      299,  299,    3,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,

      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301
    } ;

static const flex_int16_t yy_chk[836] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    5,    8,    5,   11,   17,   18,   17,   17,
       22,   22,   18,   11,   19,   31,   19,   19,   20,  176,
       20,   20,   31,   19,    8,   24,   24,   20,   30,   44,
       33,   11,   33,   19,   30,   34,   42,   20,   42,   30,
       34,   46,   55,   50,   53,   46,   53,   53,   55,  169,

       44,   50,   54,   55,   54,   54,  168,   56,   82,   56,
       85,   54,   58,   58,   61,   61,   46,   56,   85,   50,
       57,   54,   57,   57,   80,   60,   82,   60,   86,   57,
       60,   60,   87,   97,   97,   88,   85,   88,   88,   57,
       89,  158,   89,   89,  157,   80,   86,   90,   91,   90,
       87,   92,   90,   90,   91,   93,   94,   92,   94,   91,
       93,   96,   92,   96,   99,   99,   94,  101,  101,  116,
       96,   96,  100,  119,  100,  100,  120,  156,  120,  120,
      121,  119,  121,  121,  122,  123,  155,  116,  126,  126,
      122,  123,  125,  154,  125,  122,  123,  140,  128,  119,

      128,  128,  125,  129,  142,  129,  129,  130,  130,  141,
      142,  141,  141,  143,  145,  142,  144,  146,  139,  143,
      145,  144,  138,  146,  143,  145,  147,  147,  146,  149,
      137,  149,  149,  150,  159,  150,  150,  151,  151,  136,
      159,  160,  161,  163,  163,  159,  135,  160,  161,  166,
      166,  134,  160,  161,  165,  132,  165,  165,  171,  171,
      173,  115,  173,  173,  174,  174,  178,  178,  180,  114,
      180,  180,  181,  181,  184,  184,  186,  113,  186,  186,
      187,  187,  189,  189,  191,  112,  191,  191,  192,  192,
      194,  194,  196,  110,  196,  196,  197,  197,  199,  199,

      201,  109,  201,  201,  202,  202,  204,  204,  206,  108,
      206,  206,  207,  207,  209,  209,  211,  107,  211,  211,
      212,  212,  214,  214,  216,  106,  216,  216,  217,  217,
      219,  219,  221,  105,  221,  221,  222,  222,  224,  224,
      226,  104,  226,  226,  227,  227,  229,  229,  231,  103,
      231,  231,  232,  232,  234,  234,  236,   81,  236,  236,
      237,  237,  239,  239,  241,   78,  241,  241,  242,  242,
      244,  244,  246,   77,  246,  246,  247,  247,  249,  249,
      251,   76,  251,  251,  252,  252,  254,  254,  256,   75,
      256,  256,  257,  257,  259,  259,  261,   74,  261,  261,

      262,  262,  264,  264,  266,   72,  266,  266,  267,  267,
      269,  269,  271,   71,  271,  271,  272,  272,  274,  274,
      276,   70,  276,  276,  277,  277,  279,  279,  281,   69,
      281,  281,  282,  282,  284,  284,  286,   68,  286,  286,
      287,  287,  289,  289,  291,   67,  291,  291,  292,  292,
      294,   66,  294,  294,  296,   65,  296,  296,  297,  294,
      297,  297,  300,   64,  300,  300,   51,  297,   48,  294,
       45,   40,   38,   37,   36,   35,   32,  297,  302,  302,
       29,  302,  302,  302,  302,  302,  302,  303,   23,  303,
       16,   14,  303,  303,  304,   10,  304,  304,  304,  305,

      305,  305,  306,    7,    3,    0,    0,  306,  306,  307,
        0,  307,    0,    0,  307,  307,  308,    0,    0,  308,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  311,  311,
      311,  312,  312,  312,  313,    0,  313,    0,    0,  313,
      313,  314,    0,    0,  314,  315,    0,  315,    0,    0,
      315,  315,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  317,  317,  317,  318,  318,  318,  319,    0,    0,
      319,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  322,

      322,  322,  323,  323,  323,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  325,  325,  325,  326,  326,  326,
      327,  327,  327,  327,  327,    0,  327,  327,  327,  328,
      328,  328,  329,  329,  329,  330,  330,  330,  331,  331,
      331,  332,  332,  332,  333,  333,  333,  334,  334,  334,
      335,  335,  335,  336,  336,  336,  337,  337,  337,  338,
      338,  338,  339,  339,  339,  340,  340,  340,  341,  341,
      341,  342,  342,  342,  343,  343,  343,  344,  344,  344,
      345,  345,  345,  346,  346,  346,  347,  347,  347,  348,
      348,  348,  349,  349,  349,  350,  350,  350,  351,  351,

      351,  352,  352,  352,  353,  353,  353,  354,  354,  354,
      355,  355,  355,  356,  356,  356,  357,  357,  357,  358,
      358,  358,  359,  359,  359,  360,  360,  360,  361,  361,
      361,  362,  362,  362,  363,  363,  363,  364,  364,  364,
      365,  365,  365,  366,  366,  366,  367,  367,  367,  368,
      368,  368,  369,  369,  369,  370,  370,  370,  371,  371,
      371,  372,  372,  372,  373,  373,  373,  374,  374,  374,
      375,  375,  375,  376,  376,  376,  377,  377,  377,  378,
      378,  378,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,

      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[37] =
    {   0,
0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "1605115_scanner.l"
#line 5 "1605115_scanner.l"
#define YYSTYPE SymbolInfo*

#include<bits/stdc++.h>
#include "1605115_symboltable.cpp"
#include "y.tab.h"

using namespace std;

int word_count=0;
int err_count = 0;

extern ofstream logfile;
extern ofstream errorfile;
extern int line_no;
//log and error file defined in parser. 


extern YYSTYPE yylval;


void updateLineNo(int line) {
	line_no = line;
}

void startLogLine(int line_no) {
	cout<< "\nLine No. " << line_no << ": ";
	
}

string getUpper(string input) {
	string yytextString(input);
	 transform(yytextString.begin(), yytextString.end(),yytextString.begin(), ::toupper);
	 return yytextString;
}

void updateLogFile(string tokenType, string symbolName, int line_no ) {
 startLogLine(line_no);
 cout << "Token <" << tokenType << "> lexeme " << symbolName << " Found" << endl;
}

void updateLogWithError(string errorType, string symbolName, int line_no) {
	cout << "\nError at line " << line_no << ": " << errorType << " " << symbolName << endl;
}


void updateTokenFile(string tokenType, string symbolName) {
	
	cout << "<" << tokenType << ", " << symbolName << "> ";
}

void IncWc(){
	word_count++;
}

SymbolInfo* getSymbolInfo(string name, string type) {
	SymbolInfo* ret = new SymbolInfo(name, type);

	return ret; 
}

string stringFormatter(string input) {

    string str = input, temp, res = "";
    int s = 0, l = str.length();
    for(int i=0; i<(l-1); i++) {
        if(str[i]=='\\') {
            temp = str.substr(s,i-s);
            char c = str[i+1];
            if(c=='a') temp.push_back('\a');
            else if(c=='b') temp.push_back('\b');
            else if(c=='n') temp.push_back('\n');
            else if(c=='t') temp.push_back('\t');
            else if(c=='f') temp.push_back('\f');
            else if(c=='v') temp.push_back('\v');
            else if(c=='r') temp.push_back('\r');
            else if(c=='0') temp.push_back('\0');
            else if(c=='\"') temp.push_back('\"');
            else if(c=='\\') temp.push_back('\\');
            res = res + temp;
            s = i+2;
        }
    }
    res = res + str.substr(s,l-s);
		

	return res;
}

#line 858 "lex.yy.c"
#line 859 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 123 "1605115_scanner.l"



#line 1080 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 302 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 783 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 126 "1605115_scanner.l"
{}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 127 "1605115_scanner.l"
{}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 132 "1605115_scanner.l"
{
	return 0;
	//todo might need to change. Not sure if we need to return.
	}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 137 "1605115_scanner.l"
{string symbol(yytext);
	updateLineNo(yylineno);
 	yylval = getSymbolInfo(symbol, "CONST_INT");
	return CONST_INT; 
 }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 143 "1605115_scanner.l"
{string symbol(yytext);
 	yylval = getSymbolInfo(symbol, "CONST_FLOAT");
	updateLineNo(yylineno);
 	return CONST_FLOAT; 	
 }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 150 "1605115_scanner.l"
{string symbol(yytext);
 //updateLogFile("CHAR_CONST", symbol, yylineno);
 symbol = stringFormatter(symbol);
 updateLineNo(yylineno);
 	
 symbol = symbol.substr(1, symbol.size() - 2);
	//yylval = getSymbolInfo(symbol, "CONST_CHAR");
	//return CONST_CHAR;
//todo probably remove this because does not match to any grammar in the parser.??
 	}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 164 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	string symbol(yytext);
	yylval = getSymbolInfo(symbol, "ADDOP");
	return ADDOP;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 171 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	string symbol(yytext);
	yylval = getSymbolInfo(symbol, "INCOP");
	return INCOP;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 178 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	string symbol(yytext);
	yylval = getSymbolInfo(symbol, "MULOP");
	return MULOP;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 185 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	string symbol(yytext);
	yylval = getSymbolInfo(symbol, "RELOP");
	return RELOP;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 192 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	string symbol(yytext);
	yylval = getSymbolInfo(symbol, "ASSIGNOP");
	return ASSIGNOP;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 199 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	string symbol(yytext);
	yylval = getSymbolInfo(symbol, "LOGICOP");
	return LOGICOP;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 206 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	string symbol(yytext);
	yylval = getSymbolInfo(symbol, "BITOP");
	return BITOP;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 213 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	string symbol(yytext);
	yylval = getSymbolInfo(symbol, "NOT");
	return NOT;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 220 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	string symbol(yytext);
		yylval = getSymbolInfo(symbol, "LPAREN");

	return LPAREN; 
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 228 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	string symbol(yytext);
	yylval = getSymbolInfo(symbol, "RPAREN");
	return RPAREN; 
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 235 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	string symbol(yytext);
	yylval = getSymbolInfo(symbol, "LCURL");
	return LCURL; 
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 242 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	string symbol(yytext);
	yylval = getSymbolInfo(symbol, "RCURL");
	return RCURL;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 249 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	string symbol(yytext);
	yylval = getSymbolInfo(symbol, "LTHIRD");
	return LTHIRD;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 256 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	string symbol(yytext);
	yylval = getSymbolInfo(symbol, "RTHIRD");
	return RTHIRD; 
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 263 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	string symbol(yytext);
	yylval = getSymbolInfo(symbol, "COMMA");
	return COMMA; 
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 270 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	string symbol(yytext);
	yylval = getSymbolInfo(symbol, "SEMICOLON");
	return SEMICOLON;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 277 "1605115_scanner.l"
{ updateLineNo(yylineno);
 	
	string yyString(yytext); string yytextString = getUpper(yyString);
	//startLogLine(yylineno); logstream << "Token <" << yytextString << "> Lexeme " << yytext << " found" << endl;
	//tokenstream << "<" << yytextString << "> ";
	//if|for|do|int|float|void|switch|else|default|while|break|char|double|return|case|continue
	
		yylval = getSymbolInfo(yyString, "KEYWORD");

	if(yytextString == "IF") {
		return IF;
	} else if (yytextString == "FOR") {
		return FOR;
	} else if (yytextString == "DO" ) {
		return DO;
	} else if (yytextString == "INT") {
		return INT;
	} else if (yytextString == "FLOAT") {
		return FLOAT;
	} else if (yytextString == "VOID") {
		return VOID;
	} else if (yytextString == "SWITCH") {
		return SWITCH;
	} else if (yytextString == "ELSE") {
		return ELSE;
	} else if (yytextString == "DEFAULT") {
		return DEFAULT;
	} else if (yytextString == "WHILE") {
		return WHILE;
	} else if (yytextString == "BREAK") {
		return BREAK;
	} else if (yytextString == "CHAR") {
		return CHAR;
	} else if (yytextString == "DOUBLE") {
		return DOUBLE;
	} else if (yytextString == "RETURN") {
		return RETURN;
	} else if (yytextString == "CASE") {
		return CASE;
	} else if (yytextString == "CONTINUE") {
		return CONTINUE;
	}
	
}
	YY_BREAK
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
#line 322 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	string symbol(yytext);

}
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 327 "1605115_scanner.l"
{updateLineNo(yylineno);
 	string symbol(yytext); }
	YY_BREAK
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 332 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	
 }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 338 "1605115_scanner.l"
{updateLineNo(yylineno);
 	 string symbol(yytext);  
yylval = getSymbolInfo(symbol, "ID");
return ID; 
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 348 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	//INVALID PREFIX ON ID OR INVALID SUFFIX ON NUMBER
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 353 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	//TOO MANY DECILMAL POINT ERROR 
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 358 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	//MULTI CHARACTER COUNT ERROR 
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 363 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	//EMPTY CHARACTER CONSTANT ERROR 
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 368 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	//UNTERMINATE CAHRACTER ERROR 
}
	YY_BREAK
case 32:
/* rule 32 can match eol */
YY_RULE_SETUP
#line 373 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	//UNTERMINATED STRING ERROR 

}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 380 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	//ILL FORMED NUMBER 
}
	YY_BREAK
case 34:
/* rule 34 can match eol */
YY_RULE_SETUP
#line 385 "1605115_scanner.l"
{updateLineNo(yylineno);
 	
	//UNFINISHED COMMENT 
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 392 "1605115_scanner.l"
{ updateLineNo(yylineno);
 	
	//UNRECOGNIZED CHARACTER
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 397 "1605115_scanner.l"
ECHO;
	YY_BREAK
#line 1521 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 302 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 302 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 301);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 397 "1605115_scanner.l"



